INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SIGN_IN','1','Sign in',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_YO_KART','1','Yokart',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SIGN_IN_WITH_EMAIL','1','Sign in with Email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SIGN_IN_WITH_SOCIAL','1','Sign in with Social',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_FORGOT_PASSWORD','1','Forgot Password?',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_USERNAME_OR_EMAIL','1','Username/Email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CREATE_AN_ACCOUNT','1','Create an account',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_USERMAME','1','Username',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ALREADY_HAVE_AN_ACCOUNT','1','Already have an account',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_AGREE_TERMS_CONDITIONS','1','I Agree to the Terms of services and Privacy Policy',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SIGN_UP','1','Sign up',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ENTER_YOUR_EMAIL_RESET_YOUR_PASSWORD','1','Enter your email to reset your password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PROCEED','1','Proceed',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SIGN_IN_ACCOUNT_WITH_SOCIAL','1','Sign in an account with social',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_NETWORK_LOSS_ERROR','1','To use Yokart App,turn on mobile data or connect to Wi-Fi',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_PASSWORD','1','Please Enter your password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_REGISTERED_EMAIL_ADDRESS','1','Please enter your registered email address',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_NAME','1','Please enter your name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_USERNAME','1','Please enter your username',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_EMAIL_ADDRESS','1','Please enter your email address',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_VALID_EMAIL','1','Please enter valid email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_PHONE_NUMBER','1','Please enter phone number',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CONFIRM_PASSWORD_DOES_NOT_MATCH','1','Confirm password does not match',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_WITHDRAW','1','Withdraw',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ADD_MONEY','1','Add Money',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_YOU_DONT_HAVE_SUFFICIENT_WALLET_BALANCE','1',"You don't have sufficient wallet balance",2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CREDIT','1','Credit',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_DEBIT','1','Debit',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_WITHDRWAL_AMOUNT','1','Please enter withdrawal amount',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_VALID_AMOUNT','1','Please enter valid amount',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_BANK_NAME','1','Please enter bank name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_ACCOUNT_HOLDER_NAME','1','Please enter account holder name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_ACCOUNT_NUMBER','1','Please enter account number',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_IFSC_CODE','1','Please enter IFSC code',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_SELECT_COUNTRY_NAME','1','Please select country name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_SELECT_STATE_NAME','1','Please select state name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_CURRENT_PASSWORD','1','Please enter your current password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_NEW_PASSWORD','1','Please enter your new password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_YOUR_PASSWORD_MUST_BE_EIGHT_CHARACTERS','1','Your password must be eight characters',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_CONFIRM_PASSWORD','1','Please enter confirm password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_YOUR_NEW_EMAIL','1','Please enter your new email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_CONFIRM_EMAIL','1','Please enter confirm email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CONFIRM_EMAIL_DOES_NOT_MATCH','1','Confirm email does not match',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_SELECT_PAYMENT_METHOD','1','Please Select Payment Method',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_VALID_PHONE_NUMBER','1','Please enter valid phone number',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_NEW_EMAIL','1','New Email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_CONFIRM_NEW_EMAIL','1','Confirm New Email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_CURRENT_PASSWORD','1','Current Password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_NEW_PASSWORD','1','New Password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_BANK_NAME','1','Bank Name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_ACCOUNT_HOLDER_NAME','1','Account Holder Name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_ACCOUNT_NUMBER','1','Account Number',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_IFSC_CODE','1','IFSC Code',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_CUSTOMER_NAME','1','Customer Name',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_PHONE_NUMBER','1','Phone Number',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_DATE_OF_BIRTH','1','Date of Birth',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_COUNTRY','1','Country',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_STATE','1','State',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HINT_CITY','1','City',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_YOU_HAVE_NO_ITEMS_FAVORITE_LIST','1','You have no items in your favorite list',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_LOGIN_TO_ADD_ITEMS_IN_YOUR_FAVORITE','1','Login to add items in your favorite',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_THERE_ARE_NO_ITEMS_IN_YOUR_FAVORITE_LIST','1','There are no items in your favorite list',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_FAVOURITE','1','Favorites',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_REQUETS','1','Requests',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_RETURN','1','Return',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_RETURN_REQUEST_DETAILS','1','Return Request Detail',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_FEATRURE_CATEGORIES','1','Feature Categories',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CHANGE_PASSWORD','1','Change Password',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CHANGE_EMAIL','1','Change Email',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_BANK_INFO','1','Bank Info',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PAYMENT_METHODS','1','Payment Methods',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_MY_ORDERS','1','My Orders',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ADDRESS_LIST','1','Addresses',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_DELIVERY_ADDRESSES','1','Delivery Addresses',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_FEATURE_CATEGORIES','1','Feature Categories',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SHIPPING_SUMMERY','1','Shipping summary',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CHANGE_CURRENCY','1','Change Currency',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ZIP','1','Zip',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_LABEL_ID','1','ID',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_DATE','1','Date',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SELECT_SHIPPING','1','Select Shipping',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_DONE','1','Done',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_OPTIONS','1','Options',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_WISHLIST','1','Wishlist',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_LOGIN_TO_ADD_ITEMS_IN_WISHLIST','1','Please login to add items in Favorite',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PRODUCTS_NOT_AVIABLE','1','Products not Available',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_WRITE_YOUR_MESSAGE','1','Write Your Message',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_SUBJECT','1','Please enter subject',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_MESSAGE','1','Please enter message',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_HELPFUL','1','Helpful',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_UNHELPFUL','1','Unhelpful',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_WANT_MORE_OFFERS_OR_LESS','1','Want more offers or less?',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_TYPE_MESSAGE_HERE','1','Type message here',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_CHOOSE_IMAGE','1','Choose Image',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_REMOVE_IMAGE','1','Remove Image',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_REWARDS_POINTS_AVIABLE_FOR_THIS_ORDER','1','Rewards Points Available for this order',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_APPLIED_WALLET_CREDIT','1','Applied Wallet Credit',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ADD_REVIEW','1','Add Review',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_REVIEW_THE_PRODUCT','1','Please Review the Product',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_FILL_ALL_THE_MANDATORY_DATA','1','Please fill all the mandatory data',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_SELECT_SHIPPING_ADDRESS','1','Please select shipping address',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_DELETE_ADDRESS','1','Delete Address',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_ADDRESS','1','Are you sure you want to delete this address?',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SUMBIT','1','Submit',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ADDRESS','1','Address',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_YOUR_CART_IS_EMPTY','1','Your cart is empty',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ADD_ITEMS_TO_IT_NOW','1','Add items to it now',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_YOUR_WISHLIST_IS_EMPTY','1','Your wishlist is empty',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_THERE_ARE_NO_ITEMS_IN_WISHLIST','1','There are no items in your wishlist',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_LOGIN_TO_ADD_ITEMS_IN_YOUR_WISHLIST','1','Login to add items in your wishlist',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_PROMO_CODE','1','Please enter Coupon code',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SELECT_ANOTHER_ADDRESS','1','Please Select Another Address',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SOMETHING_WENT_WRONG','1','Something went wrong',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_ENTER_VALID_REWARD_POINT','1','Please enter valid reward point',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_YOUR_RECENT_PURCHASE','1','Your recent purchase',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SELECT_ANOTHER_PAYMENT_METHOD','1','Select another payment method',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_REACHED_DOWNLOAD_LIMIT','1','You have reached download limit',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_DOWNLOAD_FILE_DATE_EXPIRE','1','Download file date expire',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_SUBTOTAL','1','Sub Total',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_PLEASE_SELECT_SHIPPING_METHOD','1','Please Select Shipping Method',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_VIEW_MORE_SELLERS','1','View more sellers',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_ASK_QUESTIONS','1','Ask Questions',2);
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_caption`, `label_type`) VALUES ('APP_NO_DATA_FOUND','1','No Data Found',2);

INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_YO_KART','2',2,'Yokart');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SIGN_IN','2', 2,'تسجيل الدخول');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SIGN_IN_WITH_EMAIL','2', 2,'تسجيل الدخول مع البريد الإلكتروني');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SIGN_IN_WITH_SOCIAL','2', 2,'تسجيل الدخول مع الاجتماعي');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_FORGOT_PASSWORD','2', 2,'هل نسيت كلمة المرور؟');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_USERNAME_OR_EMAIL','2', 2,'اسم المستخدم / البريد الإلكتروني');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CREATE_AN_ACCOUNT','2', 2,'انشئ حساب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_USERMAME','2', 2,'اسم المستخدم');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ALREADY_HAVE_AN_ACCOUNT','2', 2,'هل لديك حساب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_AGREE_TERMS_CONDITIONS','2', 2,'أوافق على شروط الخدمة و سياسة الخصوصية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SIGN_UP','2', 2,'سجل');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ENTER_YOUR_EMAIL_RESET_YOUR_PASSWORD','2', 2,'أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور الخاصة بك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PROCEED','2', 2,'تقدم');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SIGN_IN_ACCOUNT_WITH_SOCIAL','2', 2,'تسجيل الدخول حساب مع الاجتماعية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_NETWORK_LOSS_ERROR','2', 2,'لاستخدام Yokart التطبيقات، تشغيل البيانات المتنقلة أو اتصال واي فاي');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_PASSWORD','2', 2,'من فضلك أدخل رقمك السري');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_REGISTERED_EMAIL_ADDRESS','2', 2,'يرجى إدخال عنوان بريدك الإلكتروني المسجل');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_NAME','2', 2,'يرجى إدخال اسمك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_USERNAME','2', 2,'الرجاء إدخال اسم المستخدم');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_EMAIL_ADDRESS','2', 2,'الرجاء إدخال عنوان البريد الإلكتروني الخاص بك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_VALID_EMAIL','2', 2,'الرجاء إدخال بريد إلكتروني صحيح');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_PHONE_NUMBER','2', 2,'الرجاء إدخال رقم الهاتف');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CONFIRM_PASSWORD_DOES_NOT_MATCH','2', 2,'لا يتطابق مع تأكيد كلمة المرور');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_WITHDRAW','2', 2,'سحب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ADD_MONEY','2', 2,'إضافة المال');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_YOU_DONT_HAVE_SUFFICIENT_WALLET_BALANCE','2', 2,'ليس لديك رصيد المحفظة كافية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CREDIT','2', 2,'ائتمان');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_DEBIT','2', 2,'مدين');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_WITHDRWAL_AMOUNT','2', 2,'الرجاء إدخال المبلغ المسحوب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_VALID_AMOUNT','2', 2,'الرجاء إدخال مبلغ صالح');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_BANK_NAME','2', 2,'الرجاء إدخال اسم البنك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_ACCOUNT_HOLDER_NAME','2', 2,'الرجاء إدخال اسم صاحب الحساب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_ACCOUNT_NUMBER','2', 2,'الرجاء إدخال رقم الحساب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_IFSC_CODE','2', 2,'الرجاء إدخال رمز IFSC');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_SELECT_COUNTRY_NAME','2', 2,'يرجى تحديد اسم البلد');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_SELECT_STATE_NAME','2', 2,'يرجى تحديد اسم الدولة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_CURRENT_PASSWORD','2', 2,'الرجاء إدخال كلمة المرور الحالية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_NEW_PASSWORD','2', 2,'الرجاء إدخال كلمة المرور الجديدة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_YOUR_PASSWORD_MUST_BE_EIGHT_CHARACTERS','2', 2,'يجب أن تكون كلمة المرور ثمانية أحرف');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_CONFIRM_PASSWORD','2', 2,'الرجاء إدخال تأكيد كلمة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_YOUR_NEW_EMAIL','2', 2,'يرجى إدخال البريد الإلكتروني الجديد');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_CONFIRM_EMAIL','2', 2,'الرجاء إدخال تأكيد البريد الإلكتروني');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CONFIRM_EMAIL_DOES_NOT_MATCH','2', 2,'لا يتطابق مع تأكيد البريد الإلكتروني');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_SELECT_PAYMENT_METHOD','2', 2,'الرجاء اختيار طريقة الدفع');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_VALID_PHONE_NUMBER','2', 2,'الرجاء إدخال رقم هاتف صحيح');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_NEW_EMAIL','2', 2,'بريد إلكتروني جديد');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_CONFIRM_NEW_EMAIL','2', 2,'تأكيد جديد البريد الإلكتروني');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_CURRENT_PASSWORD','2', 2,'كلمة المرور الحالية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_NEW_PASSWORD','2', 2,'كلمة سر جديدة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_BANK_NAME','2', 2,'اسم البنك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_ACCOUNT_HOLDER_NAME','2', 2,'اسم صاحب الحساب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_ACCOUNT_NUMBER','2', 2,'رقم حساب');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_IFSC_CODE','2', 2,'كود IFSC');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_CUSTOMER_NAME','2', 2,'اسم الزبون');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_PHONE_NUMBER','2', 2,'رقم الهاتف');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_DATE_OF_BIRTH','2', 2,'تاريخ الولادة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_COUNTRY','2', 2,'بلد');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_STATE','2', 2,'حالة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HINT_CITY','2', 2,'مدينة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_YOU_HAVE_NO_ITEMS_FAVORITE_LIST','2', 2,'لديك أي سلع في قائمة المفضلة لديك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_LOGIN_TO_ADD_ITEMS_IN_YOUR_FAVORITE','2', 2,'تسجيل الدخول لإضافة عناصر في المفضلة لديك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_THERE_ARE_NO_ITEMS_IN_YOUR_FAVORITE_LIST','2', 2,'لا توجد أي عناصر في قائمة المفضلة لديك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_FAVOURITE','2', 2,'المفضلة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_REQUETS','2', 2,'طلبات');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_RETURN','2', 2,'إرجاع');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_RETURN_REQUEST_DETAILS','2', 2,'عودة طلب التفاصيل');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_FEATRURE_CATEGORIES','2', 2,'ميزة الفئات');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CHANGE_PASSWORD','2', 2,'تغيير كلمة المرور');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CHANGE_EMAIL','2', 2,'تغيير البريد الالكتروني');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_BANK_INFO','2', 2,'بنك المعلومات');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PAYMENT_METHODS','2', 2,'طرق الدفع');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_MY_ORDERS','2', 2,'طلباتي');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ADDRESS_LIST','2', 2,'عناوين');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_DELIVERY_ADDRESSES','2', 2,'عناوين تسليم');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_FEATURE_CATEGORIES','2', 2,'ميزة الفئات');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SHIPPING_SUMMERY','2', 2,'ملخص الشحن');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CHANGE_CURRENCY','2', 2,'تغيير العملة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ZIP','2', 2,'الرمز البريدي');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_LABEL_ID','2', 2,'هوية شخصية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_DATE','2', 2,'تاريخ');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SELECT_SHIPPING','2', 2,'أختار الشحن');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_DONE','2', 2,'منجز');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_OPTIONS','2', 2,'خيارات');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_WISHLIST','2', 2,'قائمة الرغبات');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_LOGIN_TO_ADD_ITEMS_IN_WISHLIST','2', 2,'الرجاء تسجيل الدخول لإضافة عناصر في المفضلة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PRODUCTS_NOT_AVIABLE','2', 2,'المنتجات غير متوفرة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_WRITE_YOUR_MESSAGE','2', 2,'اكتب رسالتك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_SUBJECT','2', 2,'الرجاء إدخال موضوع');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_MESSAGE','2', 2,'يرجى كتابة رسالة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_HELPFUL','2', 2,'معاون، مساعد، مفيد، فاعل خير');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_UNHELPFUL','2', 2,'غير مساعد');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_WANT_MORE_OFFERS_OR_LESS','2', 2,'نريد المزيد من العروض أو أقل؟');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_TYPE_MESSAGE_HERE','2', 2,'نوع الرسالة هنا');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_CHOOSE_IMAGE','2', 2,'اختر صورة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_REMOVE_IMAGE','2', 2,'إزالة الصورة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_REWARDS_POINTS_AVIABLE_FOR_THIS_ORDER','2', 2,'المكافآت نقاط المتوفرة لهذا النظام');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_APPLIED_WALLET_CREDIT','2', 2,'محفظة الائتمان التطبيقية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ADD_REVIEW','2', 2,'إضافة مراجعة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_REVIEW_THE_PRODUCT','2', 2,'الرجاء مراجعة المنتج');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_FILL_ALL_THE_MANDATORY_DATA','2', 2,'يرجى ملء جميع البيانات الإلزامية');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_SELECT_SHIPPING_ADDRESS','2', 2,'يرجى اختيار عنوان الشحن');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_DELETE_ADDRESS','2', 2,'حذف عنوان');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_ADDRESS','2', 2,'هل أنت متأكد أنك تريد حذف هذا العنوان؟');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SUMBIT','2', 2,'تقديم');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ADDRESS','2', 2,'عنوان');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_YOUR_CART_IS_EMPTY','2', 2,'عربة التسوق فارغة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ADD_ITEMS_TO_IT_NOW','2', 2,'إضافة عناصر إلى الآن');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_YOUR_WISHLIST_IS_EMPTY','2', 2,'قائمة رغباتك فارغة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_THERE_ARE_NO_ITEMS_IN_WISHLIST','2', 2,'لا توجد أي عناصر لسلة المفضلة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_LOGIN_TO_ADD_ITEMS_IN_YOUR_WISHLIST','2', 2,'تسجيل الدخول لإضافة العناصر الموجودة في سلة المفضلة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_PROMO_CODE','2', 2,'الرجاء إدخال رمز القسيمة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SELECT_ANOTHER_ADDRESS','2', 2,'الرجاء اختيار عنوان آخر');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SOMETHING_WENT_WRONG','2', 2,'هناك خطأ ما');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_ENTER_VALID_REWARD_POINT','2', 2,'الرجاء إدخال نقطة مكافأة صالحة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_YOUR_RECENT_PURCHASE','2', 2,'مؤخرا شرائك');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SELECT_ANOTHER_PAYMENT_METHOD','2', 2,'تحديد طريقة دفع أخرى');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_REACHED_DOWNLOAD_LIMIT','2', 2,'لقد وصلت إلى حد تحميل');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_DOWNLOAD_FILE_DATE_EXPIRE','2', 2,'تحميل ملف التاريخ تنتهي');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_SUBTOTAL','2', 2,'المجموع الفرعي');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_PLEASE_SELECT_SHIPPING_METHOD','2', 2,'الرجاء اختيار طريقة الشحن');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_VIEW_MORE_SELLERS','2', 2,'شاهد المزيد من البائعين');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_ASK_QUESTIONS','2', 2,'اسال اسئلة');
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ('APP_NO_DATA_FOUND','2', 2,'لاتوجد بيانات');

INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_OFF_UPTO","1", 2, "Off upto");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_OFF_UPTO","2", 2, "قبالة تصل");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_CHANGE_LANGUAGE","1", 2, "Change Language");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_CHANGE_LANGUAGE","2", 2, "غير اللغة");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_RE_ORDER","1", 2, "Re-Order");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_RE_ORDER","2", 2, "إعادة ترتيب");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MONEY_IN_YOUR_WALLET","1", 2, "Money in your wallet");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MONEY_IN_YOUR_WALLET","2", 2, "المال في محفظتك");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_CURRENCY_UPDATED_SUCCESSFULLY","1", 2, "Currency updated successfully");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_CURRENCY_UPDATED_SUCCESSFULLY","2", 2, "العملة تجديد بنجاح");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MOVE_TO","1", 2, "Move to");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MOVE_TO","2", 2, "الانتقال إلى");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_ADD_SHIPPING","1", 2, "Add Shipping");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_ADD_SHIPPING","2", 2, "إضافة شحن");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_TO_CHANGE_LANGUAGES_CLOSE_THE_APP_AND_RESTART_IT","1", 2, "To change languages close the app and restart it.");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_TO_CHANGE_LANGUAGES_CLOSE_THE_APP_AND_RESTART_IT","2", 2, "لتغيير اللغات إغلاق التطبيق وإعادة تشغيله.");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_CLOSE","1", 2, "Close");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_CLOSE","2", 2, "قريب");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MIN_PRICE","1", 2, "Min. Price");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MIN_PRICE","2", 2, "دقيقة. السعر");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MAX_PRICE","1", 2, "Max. Price");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_MAX_PRICE","2", 2, "ماكس. السعر");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_PLEASE_LOGIN_SEND_TO_SHOP","1", 2, "Please login send message to shop");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_PLEASE_LOGIN_SEND_TO_SHOP","2", 2, "الرجاء الدخول إرسال رسالة للتسوق");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_SELECT","1", 2, "Select");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_SELECT","2", 2, "تحديد");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_SERVER_ERROR","1", 2, "Server Error");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_SERVER_ERROR","2", 2, "خطأ في الخادم");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_PLEASE_TRY_AGAIN","1", 2, "Please try again later");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_PLEASE_TRY_AGAIN","2", 2, "الرجاء معاودة المحاولة في وقت لاحق");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_INTERNET_CONNECTION","1", 2, "The Internet connection appears to be offline.");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_INTERNET_CONNECTION","2", 2, "ويبدو أن الاتصال بالإنترنت لتكون حاليا.");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_NETWORK_ERROR","1", 2, "Network Error");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_NETWORK_ERROR","2", 2, "خطأ في الشبكة");

UPDATE `tbl_language_labels` SET `label_caption`="Okay",`label_type`=2 WHERE `label_key`="APP_OK" AND `label_lang_id`="1";
UPDATE `tbl_language_labels` SET `label_caption`="حسنا",`label_type`=2 WHERE `label_key`="APP_OK" AND `label_lang_id`="2";

INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_READ_MORE","1", 2,"Read More");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_READ_MORE","2", 2,"اقرأ أكثر");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_DOWNLOAD","1", 2,"Download");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_DOWNLOAD","2", 2,"تحميل");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_TERMS_OF_SERVICES","1", 2,"Terms of Services");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_TERMS_OF_SERVICES","2", 2,"شروط الخدمة");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_SOLD_OUT","1", 2,"Sold Out");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_SOLD_OUT","2", 2,"بيعت كلها");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_YOUR_FAVORITE_IS_EMPTY","1", 2,"Your favorite list is empty?");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_YOUR_FAVORITE_IS_EMPTY","2", 2,"قائمة المفضلة لديك فارغة؟");

INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_AND","1", 2,"And");
INSERT INTO `tbl_language_labels`(`label_key`, `label_lang_id`, `label_type`, `label_caption`) VALUES ("APP_AND","2", 2,"و");